# Generated by Django 3.0.3 on 2020-06-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmanageplanmodel',
            name='dataTime',
            field=models.DateTimeField(blank=True, help_text='当前任务执行的时间', null=True, verbose_name='执行时间'),
        ),
        migrations.AlterField(
            model_name='productmanageplanmodel',
            name='dataTime',
            field=models.DateTimeField(blank=True, help_text='当前任务执行的时间', null=True, verbose_name='执行时间'),
        ),
        migrations.AlterField(
            model_name='semifinishedmanageplanmodel',
            name='dataTime',
            field=models.DateTimeField(blank=True, help_text='当前任务执行的时间', null=True, verbose_name='执行时间'),
        ),
    ]
