# Generated by Django 3.0.3 on 2020-10-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeanAlterRecordModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uri', models.CharField(blank=True, help_text='当前审核记录属于资源的名称', max_length=32, null=True, verbose_name='资源名称')),
                ('desc', models.TextField(blank=True, help_text='当前信息未列出的字段项，可以在此字段描述.每一项用;隔开', null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='当前信息创建的时间,后台会自动填充此字段', verbose_name='创建时间')),
                ('create_user', models.CharField(help_text='创建当前信息的账号名称', max_length=32, verbose_name='创建账号')),
            ],
            options={
                'verbose_name': '精益管理－审核记录',
                'verbose_name_plural': '精益管理－审核记录',
                'db_table': 'LeanAlterRecordModel',
            },
        ),
        migrations.CreateModel(
            name='LeanAuditRecordModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uri', models.CharField(blank=True, help_text='当前操作的资源名称', max_length=32, null=True, verbose_name='资源名称')),
                ('uri_id', models.CharField(blank=True, help_text='当前操作的资源索引项', max_length=16, null=True, verbose_name='资源索引')),
                ('time', models.DateTimeField(auto_now_add=True, help_text='进行操作的时间', verbose_name='时间')),
                ('classes', models.CharField(blank=True, help_text='进行操作的类别', max_length=16, null=True, verbose_name='类别')),
                ('user', models.CharField(blank=True, help_text='进行操作的账号名称', max_length=32, null=True, verbose_name='账号')),
                ('result', models.CharField(blank=True, help_text='进行操作的结果', max_length=16, null=True, verbose_name='结果')),
                ('content', models.TextField(blank=True, help_text='进行当前操作具体涉及哪些内容', null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '精益管理－操作记录',
                'verbose_name_plural': '精益管理－操作记录',
                'db_table': 'LeanAuditRecordModel',
                'permissions': {('read_leanauditrecordmodel', 'Can read 精益管理－操作记录')},
            },
        ),
        migrations.CreateModel(
            name='LeanFileModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(help_text='当前APP文件', upload_to='lean/file/')),
                ('file_name', models.CharField(blank=True, help_text='当前文件的名称', max_length=32, null=True, verbose_name='文件名')),
                ('uri', models.CharField(blank=True, help_text='当前文件属于资源的名称', max_length=32, null=True, verbose_name='资源名')),
                ('desc', models.TextField(blank=True, help_text='当前信息未列出的字段项，可以在此字段描述.每一项用;隔开', null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='当前信息创建的时间,后台会自动填充此字段', verbose_name='创建时间')),
                ('create_user', models.CharField(help_text='创建当前信息的账号名称', max_length=32, verbose_name='创建账号')),
            ],
            options={
                'verbose_name': '精益管理－文件项',
                'verbose_name_plural': '精益管理－文件项',
                'db_table': 'LeanFileModel',
            },
        ),
        migrations.CreateModel(
            name='LeanImageModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(help_text='当前APP照片', upload_to='lean/image/')),
                ('image_name', models.CharField(blank=True, help_text='当前图片的名称', max_length=32, null=True, verbose_name='照片名')),
                ('uri', models.CharField(blank=True, help_text='当前图片属于资源的名称', max_length=32, null=True, verbose_name='资源名')),
                ('desc', models.TextField(blank=True, help_text='当前信息未列出的字段项，可以在此字段描述.每一项用;隔开', null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='当前信息创建的时间,后台会自动填充此字段', verbose_name='创建时间')),
                ('create_user', models.CharField(help_text='创建当前信息的账号名称', max_length=32, verbose_name='创建账号')),
            ],
            options={
                'verbose_name': '精益管理－图片项',
                'verbose_name_plural': '精益管理－图片项',
                'db_table': 'LeanImageModel',
            },
        ),
        migrations.CreateModel(
            name='LeanBoardModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='精益看板名称(建议唯一)', max_length=32, null=True, verbose_name='名称')),
                ('code', models.CharField(help_text='精益看板编号(必须唯一)', max_length=32, unique=True, verbose_name='编码')),
                ('state', models.CharField(choices=[('新建', '新建'), ('审核中', '审核中'), ('使用中', '使用中'), ('作废', '作废')], default='新建', help_text='当前信息的使用状态', max_length=16, verbose_name='状态')),
                ('desc', models.TextField(blank=True, help_text='当前信息未列出的字段项，可以在此字段描述.每一项用;隔开', null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='当前信息创建的时间,后台会自动填充此字段', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='当前信息最后的更新时间,后台会自动填充此字段', verbose_name='更新时间')),
                ('create_user', models.CharField(help_text='创建当前信息的账号名称', max_length=32, verbose_name='创建账号')),
                ('auditor', models.CharField(help_text='可对当前信息进行审核的账号名称', max_length=32, verbose_name='审核账号')),
                ('alter', models.ManyToManyField(blank=True, help_text='当前信息的审核记录', to='lean.LeanAlterRecordModel', verbose_name='审核记录')),
                ('file', models.ManyToManyField(blank=True, help_text='当前看板的文件信息', to='lean.LeanFileModel', verbose_name='文件')),
                ('image', models.ForeignKey(help_text='当前看板的缩略图', on_delete=django.db.models.deletion.CASCADE, to='lean.LeanImageModel', verbose_name='缩略图')),
            ],
            options={
                'verbose_name': '精益管理－精益看板定义',
                'verbose_name_plural': '精益管理－精益看板定义',
                'db_table': 'LeanBoardModel',
                'permissions': {('read_leanboardmodel', 'Can read 精益管理－精益看板定义'), ('admin_leanboardmodel', 'Can admin 精益管理－精益看板定义')},
            },
        ),
    ]
